routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
*/

use Illuminate\Support\Facades\Route;

// Routes for employees
Route::resource('employees', 'UsersController')->except('show');
Route::prefix('employees')->group(function () {
    // Views
    Route::get('edit/{id}', ['uses' => 'UsersController@editTrahedEmployee', 'as' => 'editTrashedEmployee']);
    Route::get('disabled', ['uses' => 'UsersController@viewTrashedEmployees', 'as' => 'viewTrashedEmployees']);
});

// Routes for companies
Route::resource('companies', 'CompaniesController')->except('show');
Route::prefix('companies')->group(function () {
    Route::get('disabled', ['uses' => 'CompaniesController@viewTrashedCompanies', 'as' => 'viewTrashedCompanies']);
});

// Routes for searching employees
Route::get('search', ['uses' => 'UsersController@searchEmployees', 'as' => 'searchEmployees']);
Route::get('searchTrashedEmployees', ['uses' => 'UsersController@searchTrashedEmployees', 'as' => 'searchTrashedEmployees']);

// Routes for delete, restore and reassign employees
Route::delete('employee/{id}', ['uses' => 'UsersController@deleteEmployee', 'as' => 'deleteEmployee']);
Route::get('restore/employee/{id}', ['uses' => 'UsersController@restoreEmployee', 'as' => 'restoreEmployee']);
Route::put('reassign/employee/{user}', ['uses' => 'UsersController@reAssignEmployee', 'as' => 'reassignEmployee']);

// Routes for delete and restore companies
Route::delete('company/{id}', ['uses' => 'CompaniesController@deleteCompany', 'as' => 'deleteCompany']);
Route::get('companies/edit/{id}', ['uses' => 'CompaniesController@restoreCompany', 'as' => 'restoreCompany']);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['register' => false]);

resources/views/partials/navbar.blade.php
<nav class="navbar navbar-expand topbar static-top shadow">

    @if (auth()->check() && auth()->user()->isAdmin())
        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>
    @endif

    @guest
        <div class="sidebar-brand d-flex align-items-center justify-content-center admin-logo">
            <div class="sidebar-brand-icon rotate-n-15">
                <img src="{{ asset('defaultImages/ince.png') }}" width="55" height="55" class="d-inline-block align-top rounded" alt="">
            </div>
            <div class="sidebar-brand-text orgChart mx-3">Organogram</div>
        </div>
    @endguest
    @if (auth()->check() && !auth()->user()->isAdmin())
        <div class="sidebar-brand d-flex align-items-center justify-content-center" style="background: white">
            <div class="sidebar-brand-icon rotate-n-15">
                <img src="{{ asset('defaultImages/ince.png') }}" width="55" height="55" class="d-inline-block align-top rounded" alt="">
            </div>
            <div class="sidebar-brand-text orgChart mx-3">Organogram</div>
        </div>
    @endif

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img class="img-profile rounded-circle" src="{{asset('defaultImages/orgchart.PNG') }}">
            </a>
            <!-- Dropdown - Alerts -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                    Organogram
                </h6>
                @foreach($entities as $entity)
                    <a class="dropdown-item d-flex align-items-center" href="{{route('home', ['name' => $entity->company])}}">
                        <div class="mr-3">
                            <div class="icon-circle">
                                <i class="fa fa-link text-white"></i>
                            </div>
                        </div>
                        <div>
                            <span class="font-weight-bold">{{$entity->name}}</span>
                        </div>
                    </a>
                @endforeach
            </div>
        </li>

        <div class="topbar-divider d-none d-sm-block"></div>

        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                @if (auth()->check())
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{auth()->user()->name.' '.auth()->user()->surname}}</span>
                    <img class="img-profile rounded-circle" src="{{(auth()->user()->avatar) ? auth()->user()->avatar :  asset('defaultImages/ghost.png') }}">
                @else
                    <img class="img-profile rounded-circle" src="{{ asset('defaultImages/Login.PNG') }}">
                @endif
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                @if (auth()->check())
                    <a class="dropdown-item" href="{{route('employee.profile.index')}}">
                        <i class="fa fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        Profile
                    </a>
                @endif
                @if (!auth()->check())
                    <a class="dropdown-item" href="{{ route('login') }}">
                        <i class="fa fa-sign-in fa-sm fa-fw mr-2 text-gray-400"></i>
                        {{ __('Login') }}
                    </a>
                @endif
                @if (auth()->check())
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
                        <i class="fa fa-sign-out fa-sm fa-fw mr-2 text-gray-400"></i>
                        Logout
                    </a>
                @endif
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>

    </ul>

</nav>

resources/views/partials/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <div class="sidebar-brand d-flex align-items-center justify-content-center" style="background: white">
        <div class="sidebar-brand-icon rotate-n-15">
            <img src="{{ asset('defaultImages/ince.png') }}" width="55" height="55" class="d-inline-block align-top rounded" alt="">
        </div>
        <div class="sidebar-brand-text mx-3" style="color: #D82F3F;">Organogram</div>
    </div>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        ORGANOGRAM
    </div>

    <li class="nav-item {{ Ekko::isActiveRoute('home.*') }}">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fa fa-fw fa-cog"></i>
            <span>List Of Organogram</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                @foreach($entities as $entity)
                    <a class="collapse-item" href="{{route('home', ['name' => $entity->company])}}"><i class="fa fa-link text-danger"></i> <span>{{$entity->name}}</span></a>
                @endforeach
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        MY DETAILS
    </div>
    <li class="nav-item{{ Ekko::isActiveRoute('employee.profile.*') }}">
        <a class="nav-link collapsed" href="{{route('employee.profile.index')}}" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fa fa-user"></i>
            <span>Profile</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Interface
    </div>

    <li class="nav-item{{ Ekko::isActiveRoute('admin.employees.*') }}">
        <a class="nav-link collapsed" href="{{route('admin.employees.index')}}" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fa fa-users"></i>
            <span>Employees</span>
        </a>
    <li class="nav-item{{ Ekko::isActiveRoute('admin.companies.*') }}">
        <a class="nav-link collapsed" href="{{route('admin.companies.index')}}" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fa fa-list"></i>
            <span>Companies</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        TRASHED
    </div>

    <li class="nav-item{{ Ekko::isActive('/admin/employees/disabled') }}">
        <a class="nav-link collapsed" href="{{route('admin.viewTrashedEmployees')}}"  data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
            <i class="fa fa-trash"></i>
            <span>Trashed Employees</span>
        </a>
    </li>
    <li class="nav-item{{ Ekko::isActive('/admin/companies/disabled') }}">
        <a class="nav-link collapsed" href="{{route('admin.viewTrashedCompanies')}}"  data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
            <i class="fa fa-trash"></i>
            <span>Trashed Companies</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">
        <!-- Heading -->
        <div class="sidebar-heading">
            Excel
        </div>
    <li class="nav-item{{ Ekko::isActive('/admin/importexport') }}">
        <a class="nav-link collapsed" href="{{route('admin.importexport.index')}}"  data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
            <i class="fa fa-database"></i>
            <span>Import & Export Data</span>
        </a>
    </li>
    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">
    <div class="text-center d-none d-md-inline collapse-button">
        <button class="rounded-circle border-0" id="sidebarToggle" >
            <span></span>
            <span></span>
            <span></span>
        </button>
    </div>
</ul>

@push('scripts')
    <script src="{{ asset('js/bootstrap.min.js') }}"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarToggle').on('click', function () {
                $(this).toggleClass('active');
            });
        });
    </script>
@endpush