routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
*/

use Illuminate\Support\Facades\Route;

// Routes for employees
Route::resource('employees', 'UsersController')->except('show');
Route::prefix('employees')->group(function () {
    // Views
    Route::get('edit/{id}', ['uses' => 'UsersController@editTrahedEmployee', 'as' => 'editTrashedEmployee']);
    Route::get('disabled', ['uses' => 'UsersController@viewTrashedEmployees', 'as' => 'viewTrashedEmployees']);
});

// Routes for companies
Route::resource('companies', 'CompaniesController')->except('show');
Route::prefix('companies')->group(function () {
    Route::get('disabled', ['uses' => 'CompaniesController@viewTrashedCompanies', 'as' => 'viewTrashedCompanies']);
});

// Routes for searching employees
Route::get('search', ['uses' => 'UsersController@searchEmployees', 'as' => 'searchEmployees']);
Route::get('searchTrashedEmployees', ['uses' => 'UsersController@searchTrashedEmployees', 'as' => 'searchTrashedEmployees']);

// Routes for delete, restore and reassign employees
Route::delete('employee/{id}', ['uses' => 'UsersController@deleteEmployee', 'as' => 'deleteEmployee']);
Route::get('restore/employee/{id}', ['uses' => 'UsersController@restoreEmployee', 'as' => 'restoreEmployee']);
Route::put('reassign/employee/{user}', ['uses' => 'UsersController@reAssignEmployee', 'as' => 'reassignEmployee']);

// Routes for delete and restore companies
Route::delete('company/{id}', ['uses' => 'CompaniesController@deleteCompany', 'as' => 'deleteCompany']);
Route::get('companies/edit/{id}', ['uses' => 'CompaniesController@restoreCompany', 'as' => 'restoreCompany']);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['register' => false]);

app/Http/Controllers/Admin/CompaniesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\Alert;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateCompanyRequest;
use App\User;

class CompaniesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $entities = User::where('surname', NULL)->paginate(10);

        return view('admin.companies.index', compact('entities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\CreateCompanyRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCompanyRequest $request)
    {
        User::create($request->validated());

        Alert::crud(true, 'store');

        return redirect()->route('admin.companies.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit = User::findOrFail($id);

        return view('admin.companies.edit', compact('edit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\CreateCompanyRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CreateCompanyRequest $request, $id)
    {
        User::findOrFail($id)->update($request->validated());

        Alert::crud(true, 'update');

        return redirect()->route('admin.companies.index');
    }

    /**
     * Disables the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::findOrFail($id)->delete();

        Alert::success('Disabled successfully!');

        return redirect()->back();
    }

    /**********************************************************************************************/
    /************************Below are the methods for trashed Companies.**************************/
    /**********************************************************************************************/

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function viewTrashedCompanies()
    {
        $entities = User::where('surname', NULL)
            ->with([
                'reportto' => function($reportto) {  $reportto->withTrashed(); }
            ])
            ->onlyTrashed()
            ->paginate(10);

        return view('admin.companies.trashedcompanies.index', compact('entities'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restoreCompany($id)
    {
        $restore = User::withTrashed()->where('id', $id)->firstOrFail();

        $restore->restore();

        Alert::success('Restored successfully.');

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function deleteCompany($id)
    {
        $delete = User::withTrashed()->where('id', $id)->firstOrFail();

        if(file_exists(public_path().$delete->avatar))
        {
            unlink(public_path().$delete->avatar);
        }

        $delete->forceDelete();

        Alert::success('Deleted successfully.');

        return redirect()->back();
    }
}

resources/views/admin/companies/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="container-fluid companies">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <h4 class="font-weight-700">Register Company</h4>
                <div class="card card-shadow">
                    <div class="card-body">
                        <form method="post" action="{{route('admin.companies.store')}}" enctype="multipart/form-data">
                            @csrf
                            <div class="row justify-content-center">
                                <div class="col-md-3">
                                    <div class="form-group img-center">
                                        <img class="img img-fluid rounded-circle profile-picture" id="blah" src="{{asset('defaultImages/ghost.png')}}" />
                                    </div>
                                </div>
                            </div>
                            <div class="row justify-content-center">
                                <div class="col-md-4">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="avatar">Company Logo:</label>
                                            <hr class="devider hrlines">
                                            <input type="file" name="avatar" onchange="readURL(this);" class="form-control @error('avatar') is-invalid @enderror">
                                            @error('avatar')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="name">Company Name:</label>
                                            <hr class="devider hrlines">
                                            <input type="text" name="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" value="{{ old('name') }}" placeholder="Name">
                                            @if ($errors->has('name'))
                                                <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('name') }}</strong>
                                            </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            <button type="submit" class="btn btn-primary btn-at-media color-btn"><span><i class="fa fa-user-plus"></i></span>Submit</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('js/custom.js') }}" ></script>
@endpush

resources/views/admin/companies/edit.blade.php
@extends('layouts.master')

@section('content')
    <div class="container-fluid companies">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <h4 class="font-weight-700">Update Company</h4>
                <div class="card card-shadow">
                    <div class="card-body">
                        <form method="post" action="{{route('admin.companies.update', $edit->id)}}" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="row justify-content-center">
                                <div class="col-md-3">
                                    <div class="form-group img-center">
                                        <img class="img img-fluid rounded-circle profile-picture" id="blah" src="{{asset('defaultImages/ghost.png')}}" />
                                    </div>
                                </div>
                            </div>
                            <div class="row justify-content-center">
                                <div class="col-md-4">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="avatar">Company Logo:</label>
                                            <hr class="devider hrlines">
                                            <input type="file" name="avatar" onchange="readURL(this);" class="form-control @error('avatar') is-invalid @enderror">
                                            @error('avatar')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="name">Company Name:</label>
                                            <hr class="devider hrlines">
                                            <input type="text" name="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" value="{{ $edit->name }}" placeholder="Name">
                                            @if ($errors->has('name'))
                                                <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('name') }}</strong>
                                            </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            <button type="submit" class="btn btn-primary btn-at-media color-btn"><span><i class=" fa fa-edit fa-lg"></i></span>Update</button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('js/custom.js') }}" ></script>
@endpush

resources/views/admin/companies/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="container-fluid companies">
        <h4 class="font-weight-700">List Of Companies</h4>
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card card-shadow">
                    <div class="card-body">
                        <div class="d-md-flex flex-row">
                            <div class="add-button">
                                <a href="{{route('admin.companies.create')}}" class="btn btn-primary color-btn btn-at-media">
                                    <span><i class="fa fa-user-plus"></i></span></span>
                                    Add Company
                                </a>
                            </div>
                        </div>
                        <div class="table-responsive table-button">
                            <table class="table table-hover table-striped table-bordered table-sm" style="width: 100%;">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Logo</th>
                                    <th>Company&nbspName</th>
                                    <th>Created</th>
                                    <th>Updated</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if ($entities->count() > 0)
                                    @foreach ($entities as $item)
                                        <tr>
                                            <td>{{$item->id}}</td>
                                            <td>
                                                <img src="{{asset($item->avatar)}}" alt="" class="rounded border border-light logo">
                                            </td>
                                            <td>{{$item->name}}</td>
                                            <td>{{$item->created_at}}</td>
                                            <td>{{$item->updated_at}}</td>
                                            <td>
                                                <div class="d-flex">
                                                    <div>
                                                        <a href="{{route('admin.companies.edit', $item->id)}}" class="btn btn-success color-btn btn-sm mr-3">
                                                            <i class=" fa fa-edit fa-lg"></i>
                                                        </a>
                                                    </div>
                                                    <div>
                                                        <form method="post" action="{{route('admin.companies.destroy', $item->id)}}">
                                                            @csrf
                                                            @method('DELETE')
                                                            <button type="submit" class="btn btn-sm btn-danger">
                                                                <i class="fa fa-user-times fa-lg"></i>
                                                            </button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                @else
                                    <tr>
                                        <th colspan="6" class="text-center">No companies found</th>
                                    </tr>
                                @endif
                                </tbody>
                            </table>
                            {{ $entities->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection