routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
*/

use Illuminate\Support\Facades\Route;

// Routes for employees
Route::resource('employees', 'UsersController')->except('show');
Route::prefix('employees')->group(function () {
    // Views
    Route::get('edit/{id}', ['uses' => 'UsersController@editTrahedEmployee', 'as' => 'editTrashedEmployee']);
    Route::get('disabled', ['uses' => 'UsersController@viewTrashedEmployees', 'as' => 'viewTrashedEmployees']);
});

// Routes for companies
Route::resource('companies', 'CompaniesController')->except('show');
Route::prefix('companies')->group(function () {
    Route::get('disabled', ['uses' => 'CompaniesController@viewTrashedCompanies', 'as' => 'viewTrashedCompanies']);
});

// Routes for searching employees
Route::get('search', ['uses' => 'UsersController@searchEmployees', 'as' => 'searchEmployees']);
Route::get('searchTrashedEmployees', ['uses' => 'UsersController@searchTrashedEmployees', 'as' => 'searchTrashedEmployees']);

// Routes for delete, restore and reassign employees
Route::delete('employee/{id}', ['uses' => 'UsersController@deleteEmployee', 'as' => 'deleteEmployee']);
Route::get('restore/employee/{id}', ['uses' => 'UsersController@restoreEmployee', 'as' => 'restoreEmployee']);
Route::put('reassign/employee/{user}', ['uses' => 'UsersController@reAssignEmployee', 'as' => 'reassignEmployee']);

// Routes for delete and restore companies
Route::delete('company/{id}', ['uses' => 'CompaniesController@deleteCompany', 'as' => 'deleteCompany']);
Route::get('companies/edit/{id}', ['uses' => 'CompaniesController@restoreCompany', 'as' => 'restoreCompany']);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['register' => false]);

resources/views/admin/employees/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="container-fluid employees">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <h4 class="font-weight-700">Register Employee</h4>
                <div class="card card-shadow">
                    <div class="card-body">
                        <form method="post" action="{{route('admin.employees.store')}}" enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="name">Name:</label>
                                        <hr class="devider hrlines">
                                        <input type="text" name="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" value="{{ old('name') }}" placeholder="Name">
                                        @if ($errors->has('name'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('name') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="surname">Surname:</label>
                                        <hr class="devider hrlines">
                                        <input type="text" name="surname" class="form-control{{ $errors->has('surname') ? ' is-invalid' : '' }}" value="{{ old('surname') }}" placeholder="Surname">
                                        @if ($errors->has('surname'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('surname') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="email">E-mail</label>
                                        <hr class="devider hrlines">
                                        <input type="email" name="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" value="{{ old('email') }}" placeholder="E-mail">
                                        @if ($errors->has('email'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('email') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="phone">Mobile No:</label>
                                        <hr class="devider hrlines">
                                        <input type="text" name="phone" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}" value="{{ old('phone') }}" placeholder="Mobile">
                                        @if ($errors->has('phone'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('phone') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="work">Work No:</label>
                                        <hr class="devider hrlines">
                                        <input type="text" name="work" class="form-control{{ $errors->has('work') ? ' is-invalid' : '' }}" value="{{ old('work') }}" placeholder="Contact">
                                        @if ($errors->has('work'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('work') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="jobtitle">Job Title:</label>
                                        <hr class="devider hrlines">
                                        <input type="text" name="jobtitle" class="form-control{{ $errors->has('jobtitle') ? ' is-invalid' : '' }}" value="{{ old('jobtitle') }}" placeholder="Job Title">
                                        @if ($errors->has('jobtitle'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('jobtitle') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="division">Division:</label>
                                        <hr class="devider hrlines">
                                        <select name="division" class="form-control @error('division') is-invalid @enderror" >
                                            <option selected>Select division...</option>
                                            <option value="IMedia">IMedia</option>
                                            <option value="IBD&M">IBD&M</option>
                                            <option value="Agency">Agency</option>
                                            <option value="Shared Services">Shared Services</option>
                                        </select>
                                        @error('division')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="region">Region:</label>
                                        <hr class="devider hrlines">
                                        <select name="region" class="form-control @error('region') is-invalid @enderror"  >
                                            <option selected>Select region...</option>
                                            <option value="KZN">KZN</option>
                                            <option value="Gauteng">Gauteng</option>
                                            <option value="Western Cape">Western Cape</option>
                                        </select>
                                        @error('region')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="reportto">Report To:</label>
                                        <hr class="devider hrlines">
                                        <select name="reportto" class="form-control @error('reportto') is-invalid @enderror">
                                            <option selected>Select reportTo...</option>
                                            <optgroup label="Company">
                                                @foreach ($entities as $item)
                                                        <option value="{{$item->id}}">{{$item->name}}</option>
                                                @endforeach
                                            </optgroup>
                                            <optgroup label="Users">
                                                @foreach ($users as $item)
                                                    @if ($item->reportto !== NULL)
                                                        <option value="{{$item->id}}">{{$item->name}} {{$item->surname}}</option>
                                                    @endif
                                                @endforeach
                                            </optgroup>
                                        </select>
                                        @error('reportto')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>

                            </div>

                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="avatar">Avatar:</label>
                                        <hr class="devider hrlines">
                                        <input type="file" name="avatar" class="form-control @error('avatar') is-invalid @enderror" placeholder="Avatar">
                                        @error('avatar')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="company">Company Name:</label>
                                        <hr class="devider hrlines">
                                        <select name="company" class="form-control @error('company') is-invalid @enderror" >
                                            @foreach ($entities as $item)
                                                <option value="{{strtolower($item->name)}}">{{$item->name}}</option>
                                            @endforeach
                                        </select>
                                        @error('company')
                                        <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="admin">System Role:</label>
                                        <hr class="devider hrlines">
                                        <select name="admin" class="form-control @error('admin') is-invalid @enderror" >
                                            <option value="0" selected>User</option>
                                            <option value="1">Admin</option>
                                        </select>
                                        @error('admin')
                                        <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                            </div>

                            <button type="submit" class="btn btn-primary btn-at-media color-btn"><span><i class="fa fa-user-plus"></i></span>Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/employees/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="container-fluid employees">
        <h4 class="font-weight-700">List Of Employees</h4>
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card card-shadow">
                    <div class="card-body">
                        <div class="d-md-flex flex-row">
                            <div class="add-button">
                                <a href="{{route('admin.employees.create')}}" class="btn btn-primary color-btn btn-at-media">
                                    <span><i class="fa fa-user-plus"></i></span></span>
                                    Add Employee
                                </a>
                            </div>
                            <div class="ml-auto create">
                                <form method="get" action="{{route('admin.searchEmployees')}}">
                                    @csrf
                                    <div class="input-group">
                                        <input type="text" name="search" class="form-control" placeholder="Search">
                                        <div class="input-group-append">
                                            <button type="submit" class="btn btn-outline-secondary"><i class="fa fa-search"></i></button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-hover table-striped table-bordered table-sm" style="width: 100%;">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Surname</th>
                                    <th>Email</th>
                                    <th>Work&nbspNo</th>
                                    <th>Job&nbspTitle</th>
                                    <th>Division</th>
                                    <th>Report&nbspTo</th>
                                    <th>Region</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if ($users->count() > 0)
                                    @foreach ($users as $item)
                                        <tr>
                                            <td>{{$item->id}}</td>
                                            <td>{{$item->name}}</td>
                                            <td>{{$item->surname}}</td>
                                            <td>{{$item->email}}</td>
                                            <td>{{'+27'.ltrim($item->work, '0')}}</td>
                                            <td>{{$item->jobtitle}}</td>
                                            <td>{{$item->division}}</td>
                                            @if ($item->reportTo !== NULL)
                                                <td>{{$item->reportTo->name.' '.$item->reportTo->surname}}</td>
                                            @else
                                                <td>Unassigned</td>
                                            @endif
                                            <td>{{$item->region}}</td>
                                            <td>
                                                <div class="d-flex">
                                                    <div>
                                                        <a href="{{route('employee.profile.show', $item->id)}}" class="btn btn-primary color-btn btn-sm mr-3">
                                                            <i class="fa fa-eye fa-lg"></i>
                                                        </a>
                                                    </div>
                                                    <div>
                                                        <a href="{{route('admin.employees.edit', $item->id)}}" class="btn btn-success btn-sm mr-3">
                                                            <i class=" fa fa-edit fa-lg"></i>
                                                        </a>
                                                    </div>
                                                    <div>
                                                        <form method="post" action="{{route('admin.employees.destroy', $item->id)}}">
                                                            @csrf
                                                            @method('DELETE')
                                                            <button type="submit" class="btn btn-sm btn-danger">
                                                                <i class="fa fa-user-times fa-lg"></i>
                                                            </button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                @else
                                    <tr>
                                        <th colspan="10" class="text-center">No users found</th>
                                    </tr>
                                @endif
                                </tbody>
                            </table>
                            {{ $users->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection